#+ summary: "Access to all SensorThings resources begins at the base resource path"
#+ description: "Navigating to the base resource path will return a JSON array of the available SensorThings resource endpoints. NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ pagination: 100
#+ transform: {
#+   "value": {
#+   "name": "?name",
#+   "$anchor": "name",
#+   "url": "?url",
#+   }
#+ }

PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX bif: <bif:>

SELECT DISTINCT ?name ?url
WHERE {
     VALUES (?name ?url) {
     ("Things" <https://w3id.org/iliad/api/v1.0/Things>)
     ("Locations" <https://w3id.org/iliad/api/v1.0/Locations>)
     ("HistoricalLocations" <https://w3id.org/iliad/api/v1.0/HistoricalLocations>)
     ("Datastreams" <https://w3id.org/iliad/api/v1.0/Datastreams>)
     ("Sensors" <https://w3id.org/iliad/api/v1.0/Sensors>)
     ("Observations" <https://w3id.org/iliad/api/v1.0/Observations>)
     ("ObservedProperties" <https://w3id.org/iliad/api/v1.0/ObservedProperties>)
     ("FeaturesOfInterest" <https://w3id.org/iliad/api/v1.0/FeaturesOfInterest>)}
}