#+ summary: "Access to all SensorThings resources begins at the base resource path"
#+ description: "Navigating to the base resource path will return a JSON array of the available SensorThings resource endpoints. NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ pagination: 100
#+ transform: {
#+   "value": {
#+     "name": "?name",
#+     "url": "?url"
#+   }
#+ }


PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX bif: <bif:>

SELECT ?name ?url
WHERE {
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("Things" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/Things') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("Locations" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/Locations') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("HistoricalLocations" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/HistoricalLocations') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("Datastreams" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/Datastreams') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("Sensors" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/Sensors') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("Observations" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/Observations') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("ObservedProperties" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/ObservedProperties') AS ?url)
      } LIMIT 1
   }
   UNION
   {
      SELECT ?name ?url
      WHERE {
         ?s ?p ?o
         BIND ("FeaturesOfInterest" AS ?name)
         BIND (URI('https://w3id.org/iliad/api/v1.0/FeaturesOfInterest') AS ?url)
      } LIMIT 1
   }
}
